CREATE TABLE [dbo].[OrderStatus]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    [Name] VARCHAR(50) NOT NULL UNIQUE,
	[Description] VARCHAR(200) NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(), 
    [UpdatedAt] DATETIME NOT NULL DEFAULT GETDATE()
)
